development:
  adapter: postgresql
  encoding: unicode
  database: stage-2_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: stage-2_testing
  pool: 5
  username: myapp
  password: password1
