# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68c14f820644efc6bf058d4760fd898dbddbd6da3848519ecb9fcd66616489ba3325c5618b829eed82687ee62b269e94727f73aeff58d0881762b53b11107a68

test:
  secret_key_base: 576bc5c0f49c05a12e25cf1670a1eac1d78569d40afe4dc51055ad3f19438ad1d4e696f4c40d86f9eced4f12a3093e77ba152032ffb17546f60ebef2787c6ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
